
services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project02
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
